"""
================================================================================
ASSET URLS - URL Routing for Asset API Endpoints
================================================================================

PURPOSE:
This file defines URL patterns for Asset and DamageReport API endpoints.
It uses Django REST Framework's Router to automatically generate URLs.

WHAT IS A ROUTER?
A Router automatically generates URL patterns for ViewSets.
Instead of manually writing paths for list, create, update, delete...
the Router creates them all automatically!

HOW THE ROUTER WORKS:
router.register('assets', AssetViewSet) generates:
- GET    /api/assets/           → List all assets
- POST   /api/assets/           → Create new asset
- GET    /api/assets/<id>/      → Get single asset
- PUT    /api/assets/<id>/      → Update asset
- PATCH  /api/assets/<id>/      → Partial update asset
- DELETE /api/assets/<id>/      → Delete asset

ENDPOINTS GENERATED:
Assets (prefix: /api/):
- /api/assets/              → Asset list and create
- /api/assets/<id>/         → Asset detail, update, delete

Damage Reports (prefix: /api/):
- /api/damage-reports/       → Damage report list and create
- /api/damage-reports/<id>/  → Damage report detail, update, delete

================================================================================
"""

from django.urls import path, include

# DefaultRouter automatically generates URL patterns for ViewSets
from rest_framework.routers import DefaultRouter

from . import views

# =============================================================================
# ROUTER SETUP
# Create a router and register our ViewSets with it
# =============================================================================

router = DefaultRouter()

# Register AssetViewSet with the router
# - First arg: URL prefix ('assets' becomes /api/assets/)
# - Second arg: The ViewSet class to handle requests
# - basename: Used for generating URL names (asset-list, asset-detail, etc.)
router.register(r'assets', views.AssetViewSet, basename='asset')

# Register DamageReportViewSet with the router
# URL prefix: 'damage-reports' becomes /api/damage-reports/
router.register(r'damage-reports', views.DamageReportViewSet, basename='damage-report')

# =============================================================================
# URL PATTERNS
# Include all the URLs generated by the router
# =============================================================================
urlpatterns = [
    # Include all router-generated URLs
    # '' means no additional prefix (prefix is set in main urls.py)
    path('', include(router.urls)),
]

