# Generated by Django 4.2.7 on 2026-01-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_damagereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='damaged_quantity',
        ),
    ]
