"""
================================================================================
ROOM URLS - URL Routing for Room API Endpoints
================================================================================

PURPOSE:
This file defines URL patterns for Room API endpoints.
It uses Django REST Framework's Router to automatically generate URLs.

WHAT IS A ROUTER?
A Router automatically generates URL patterns for ViewSets.
Instead of manually writing paths for list, create, update, delete...
the Router creates them all automatically!

ENDPOINTS GENERATED (prefix: /api/rooms/):
- GET    /api/rooms/           → List all rooms
- POST   /api/rooms/           → Create new room
- GET    /api/rooms/<id>/      → Get single room
- PUT    /api/rooms/<id>/      → Update room
- PATCH  /api/rooms/<id>/      → Partial update room
- DELETE /api/rooms/<id>/      → Delete room

NOTE: The '/api/rooms/' prefix is added in the main hostel_inventory/urls.py

================================================================================
"""

from django.urls import path, include

# DefaultRouter automatically generates URL patterns for ViewSets
from rest_framework.routers import DefaultRouter

from . import views

# =============================================================================
# ROUTER SETUP
# Create a router and register our RoomViewSet with it
# =============================================================================

router = DefaultRouter()

# Register RoomViewSet with the router
# - First arg: URL prefix ('' means no additional prefix after /api/rooms/)
# - Second arg: The ViewSet class to handle requests
# - basename: Used for generating URL names (room-list, room-detail, etc.)
router.register(r'', views.RoomViewSet, basename='room')

# =============================================================================
# URL PATTERNS
# Include all the URLs generated by the router
# =============================================================================
urlpatterns = [
    # Include all router-generated URLs
    path('', include(router.urls)),
]

